### ISSUE TITLE
Rejected from AppCenter

### ISSUE THREAD

**Issue by cassidyjames** [bartzaalberg/snapcenter#1]
Thank you for your submission to AppCenter! However, we don't accept alternative app stores in AppCenter. We've updated our ["Before You Publish" guidelines](https://github.com/elementary/houston/wiki/Before-You-Publish#app-stores) to explicitly call this out.

I hope you understand. We hope to see continued updates of your existing apps and more apps from you in the future.

**Comment by danrabbit** [comment]
Just wanted to follow up and say that maybe a path forward for a similar app or similar functionality would be to do something like Eddy that could install and manage snap files without presenting it as being an alternative store.

**Comment by bartzaalberg** [comment]
That would be an awesome idea. However, i have no idea how to open an application based on a link pressed in a browser. Unfortunately https://snapcraft.io/discover/ doesn't download a file which can be used. Any tips or tricks?

**Comment by bartzaalberg** [comment]
Ok, i think i found another site where i can download snap files.
